import AppKit
import Carbon
import CoreGraphics
import Foundation

/// Contract file. Inserts text into the focused app.
@MainActor
enum TextInserter {
    /// Places `text` on the pasteboard and, if `paste` is true and post-event access is granted, sends Cmd+V.
    /// Restores the previous pasteboard contents afterwards when `restoreClipboard` is true.
    /// Returns true if the text was pasted, false if it was only copied.
    @discardableResult
    static func insert(_ text: String, paste: Bool, restoreClipboard: Bool) async -> Bool {
        guard !text.isEmpty else { return false }
        let pasteboard = NSPasteboard.general
        if #available(macOS 15.4, *), pasteboard.accessBehavior == .alwaysDeny {
            return false
        }

        let secure = IsSecureEventInputEnabled()
        let canPost = CGPreflightPostEventAccess()
        let willPaste = paste && !secure && canPost
        let willRestore = willPaste && restoreClipboard

        if willRestore, retainedClipboard == nil {
            retainedClipboard = ClipboardSnapshot.take(from: pasteboard)
        }
        let restoring = willRestore && retainedClipboard != nil

        guard write(text, to: pasteboard, transient: restoring, dictated: willPaste) else {
            return false
        }
        guard willPaste else { return false }
        guard postCommandV() else { return false }

        if restoring {
            let expected = pasteboard.changeCount
            armedChangeCount = expected
            let delay = restoreDelayNanos
            Task { @MainActor in
                try? await Task.sleep(nanoseconds: delay)
                restoreIfUnchanged(expected: expected)
            }
        }
        return true
    }

    /// True when secure input (password fields) is active and pasting would not work.
    static var secureInputActive: Bool { IsSecureEventInputEnabled() }

    private static let restoreDelayNanos: UInt64 = 600_000_000
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let generatedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private static var retainedClipboard: ClipboardSnapshot?
    private static var armedChangeCount = 0

    private static func write(_ text: String, to pasteboard: NSPasteboard, transient: Bool, dictated: Bool) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string) else { return false }
        if dictated {
            _ = item.setData(Data(), forType: concealedType)
            _ = item.setData(Data(), forType: generatedType)
            if transient {
                _ = item.setData(Data(), forType: transientType)
            }
        }
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        return pasteboard.writeObjects([item])
    }

    private static func postCommandV() -> Bool {
        let source = CGEventSource(stateID: .combinedSessionState)
        let command = CGKeyCode(kVK_Command)
        let vKey = CGKeyCode(kVK_ANSI_V)
        guard
            let commandDown = CGEvent(keyboardEventSource: source, virtualKey: command, keyDown: true),
            let vDown = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true),
            let vUp = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false),
            let commandUp = CGEvent(keyboardEventSource: source, virtualKey: command, keyDown: false)
        else {
            return false
        }
        commandDown.flags = .maskCommand
        vDown.flags = .maskCommand
        vUp.flags = .maskCommand
        commandUp.flags = []
        let tap = CGEventTapLocation.cghidEventTap
        commandDown.post(tap: tap)
        vDown.post(tap: tap)
        vUp.post(tap: tap)
        commandUp.post(tap: tap)
        return true
    }

    private static func restoreIfUnchanged(expected: Int) {
        guard armedChangeCount == expected else { return }
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount == expected, let saved = retainedClipboard else {
            retainedClipboard = nil
            armedChangeCount = 0
            return
        }
        saved.write(to: pasteboard)
        retainedClipboard = nil
        armedChangeCount = 0
    }
}

/// Every representation of the general pasteboard, so restore does not collapse types.
private struct ClipboardSnapshot {
    var items: [[(NSPasteboard.PasteboardType, Data)]]

    static func take(from pasteboard: NSPasteboard) -> ClipboardSnapshot? {
        guard let items = pasteboard.pasteboardItems else { return nil }
        var copied: [[(NSPasteboard.PasteboardType, Data)]] = []
        copied.reserveCapacity(items.count)
        for item in items {
            var pairs: [(NSPasteboard.PasteboardType, Data)] = []
            for type in item.types {
                guard let data = item.data(forType: type) else { continue }
                pairs.append((type, data))
            }
            if pairs.isEmpty, !item.types.isEmpty {
                return nil
            }
            copied.append(pairs)
        }
        return ClipboardSnapshot(items: copied)
    }

    func write(to pasteboard: NSPasteboard) {
        pasteboard.prepareForNewContents(with: [])
        guard !items.isEmpty else { return }
        var objects: [NSPasteboardItem] = []
        objects.reserveCapacity(items.count)
        for pairs in items {
            let item = NSPasteboardItem()
            for (type, data) in pairs {
                _ = item.setData(data, forType: type)
            }
            objects.append(item)
        }
        pasteboard.writeObjects(objects)
    }
}
